-- =========================================================================
-- Avalon Harvester — Schema Migration v4
-- Tambah cache table untuk per-keyword schemas (generated by DeepSeek)
-- =========================================================================

CREATE TABLE IF NOT EXISTS public.keyword_schemas (
  keyword            TEXT PRIMARY KEY,
  category           TEXT,
  schema             JSONB NOT NULL,        -- brand list, regex patterns, fuzzy aliases
  sample_names       JSONB,                 -- sample produk yang dipakai untuk generate
  llm_tokens_used    INTEGER DEFAULT 0,
  llm_model          TEXT,
  product_count      INTEGER DEFAULT 0,     -- berapa produk sudah pakai schema ini
  miss_count         INTEGER DEFAULT 0,     -- berapa produk yang regex-nya gagal
  generated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  refreshed_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_keyword_schemas_category
  ON public.keyword_schemas (category);

CREATE INDEX IF NOT EXISTS idx_keyword_schemas_refreshed
  ON public.keyword_schemas (refreshed_at);

COMMENT ON COLUMN public.keyword_schemas.schema IS
  'JSON struktur: {brands: {Canonical: [aliases]}, model_families: [...], spec_patterns: {field: regex}, spec_value_types: {field: int|float|str}}';
